swiftmailer:
    default_mailer: RTMCloudHelpdesk
    mailers:
        RTMCloudHelpdesk:
            transport: smtp
            username: helpdesk@rtmcloud.com.au
            password: Hap84910
            host: smtp.office365.com
            port: 587
            encryption: tls
            auth_mode: login
            sender_address: helpdesk@rtmcloud.com.au
            delivery_addresses: ['']
            disable_delivery: false

